Feature/listar terminales
FactorizacionPlus/Pasadita pull request #113
Opened 2024-07-06 23:04 UTC by Poncka

Listar terminales
Listar historial de entradas
Cambios visuales 
Unas cuantas cosas mas

2024-07-06 23:16 UTC, davidquintr requested changes

2024-07-06 23:16 UTC, davidquintr commented on client/.env
> +VITE_SERVER_ENDPOINT=http://192.168.1.32:8080
deshacé esta mierda

2024-07-06 23:16 UTC, davidquintr commented on client/src/components/NavigationMenu/AdminNavigationMenu.vue
> +            <span>Administrador del sistema</span>
La S en mayúscula por favor

2024-07-06 23:22 UTC, davidquintr requested changes

2024-07-06 23:22 UTC, davidquintr commented on client/src/components/Cards/AdministratorTerminalCard.vue
> +    <p class="text-lg font-medium lowercase leading-none text-blue-400">
cambiar a UPPERCASE

2024-07-06 23:22 UTC, davidquintr commented on client/src/components/NavigationMenu/DefaultNavigationMenu.vue
> +          class="absolute right-0 mt-48 w-48 rounded-b-lg border bg-white shadow-lg"
1. Remover el borde
2. Incrementar el shadow para que sea más vistoso

2024-07-06 23:22 UTC, davidquintr commented on client/src/components/NavigationMenu/DefaultNavigationMenu.vue
> +          <ul class="py-1">
Remover este padding

2024-07-06 23:28 UTC, davidquintr requested changes

2024-07-06 23:28 UTC, davidquintr commented on client/src/components/NavigationMenu/DefaultNavigationMenu.vue
Agregar esta linea al dropdown para que no se vea raro

```ts
:class="showMenu ? '' : 'active:scale-95'"
```

2024-07-06 23:28 UTC, davidquintr commented on client/src/components/NavigationMenu/DefaultNavigationMenu.vue
>        <div
Añadir `transition-all` y `active:scale-95` a los items del dropdown para que no se vea tan feo xd

2024-07-07 01:40 UTC, JezerMejia approved these changes
LGTM

2024-07-07 01:42 UTC, merged